# Generated by Django 6.1.1 on 2026-09-23 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_name', models.CharField(max_length=100)),
                ('c_duration', models.IntegerField()),
                ('c_fees', models.IntegerField()),
                ('triner_name', models.CharField(max_length=100)),
                ('start_date', models.DateField()),
                ('number_seats', models.IntegerField()),
                ('active_course', models.BooleanField(default=True)),
            ],
        ),
        migrations.DeleteModel(
            name='student',
        ),
    ]
